# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modi_ai_cloud.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modi_ai_cloud.proto',
  package='modi_cloud',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13modi_ai_cloud.proto\x12\nmodi_cloud\"F\n\x0bObjectsSend\x12\x13\n\x0btrain_array\x18\x01 \x01(\x0c\x12\x13\n\x0blabel_array\x18\x02 \x01(\x0c\x12\r\n\x05model\x18\x03 \x01(\x0c\",\n\x14TransferCompleteSend\x12\x14\n\x0c\x61sk_transfer\x18\x01 \x01(\x05\",\n\x14LearningCompleteSend\x12\x14\n\x0c\x61sk_learning\x18\x01 \x01(\x05\"/\n\x15TransferCompleteReply\x12\x16\n\x0ereply_transfer\x18\x01 \x01(\x05\"/\n\x15LearningCompleteReply\x12\x16\n\x0ereply_learning\x18\x01 \x01(\x05\"#\n\nModelReply\x12\x15\n\rtrained_model\x18\x01 \x01(\x0c\x32\x99\x01\n\x12\x44\x61ta_Model_Handler\x12>\n\x0bSendObjects\x12\x17.modi_cloud.ObjectsSend\x1a\x16.modi_cloud.ModelReply\x12\x43\n\x10SendObjectsAgain\x12\x17.modi_cloud.ObjectsSend\x1a\x16.modi_cloud.ModelReply2\xc4\x01\n\x10\x43omplete_Handler\x12W\n\x10TransferComplete\x12 .modi_cloud.TransferCompleteSend\x1a!.modi_cloud.TransferCompleteReply\x12W\n\x10LearningComplete\x12 .modi_cloud.LearningCompleteSend\x1a!.modi_cloud.LearningCompleteReplyb\x06proto3'
)




_OBJECTSSEND = _descriptor.Descriptor(
  name='ObjectsSend',
  full_name='modi_cloud.ObjectsSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_array', full_name='modi_cloud.ObjectsSend.train_array', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label_array', full_name='modi_cloud.ObjectsSend.label_array', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='modi_cloud.ObjectsSend.model', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=105,
)


_TRANSFERCOMPLETESEND = _descriptor.Descriptor(
  name='TransferCompleteSend',
  full_name='modi_cloud.TransferCompleteSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ask_transfer', full_name='modi_cloud.TransferCompleteSend.ask_transfer', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=151,
)


_LEARNINGCOMPLETESEND = _descriptor.Descriptor(
  name='LearningCompleteSend',
  full_name='modi_cloud.LearningCompleteSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ask_learning', full_name='modi_cloud.LearningCompleteSend.ask_learning', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=197,
)


_TRANSFERCOMPLETEREPLY = _descriptor.Descriptor(
  name='TransferCompleteReply',
  full_name='modi_cloud.TransferCompleteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_transfer', full_name='modi_cloud.TransferCompleteReply.reply_transfer', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=246,
)


_LEARNINGCOMPLETEREPLY = _descriptor.Descriptor(
  name='LearningCompleteReply',
  full_name='modi_cloud.LearningCompleteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_learning', full_name='modi_cloud.LearningCompleteReply.reply_learning', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=295,
)


_MODELREPLY = _descriptor.Descriptor(
  name='ModelReply',
  full_name='modi_cloud.ModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trained_model', full_name='modi_cloud.ModelReply.trained_model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=332,
)

DESCRIPTOR.message_types_by_name['ObjectsSend'] = _OBJECTSSEND
DESCRIPTOR.message_types_by_name['TransferCompleteSend'] = _TRANSFERCOMPLETESEND
DESCRIPTOR.message_types_by_name['LearningCompleteSend'] = _LEARNINGCOMPLETESEND
DESCRIPTOR.message_types_by_name['TransferCompleteReply'] = _TRANSFERCOMPLETEREPLY
DESCRIPTOR.message_types_by_name['LearningCompleteReply'] = _LEARNINGCOMPLETEREPLY
DESCRIPTOR.message_types_by_name['ModelReply'] = _MODELREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectsSend = _reflection.GeneratedProtocolMessageType('ObjectsSend', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTSSEND,
  '__module__' : 'modi_ai_cloud_pb2'
  # @@protoc_insertion_point(class_scope:modi_cloud.ObjectsSend)
  })
_sym_db.RegisterMessage(ObjectsSend)

TransferCompleteSend = _reflection.GeneratedProtocolMessageType('TransferCompleteSend', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERCOMPLETESEND,
  '__module__' : 'modi_ai_cloud_pb2'
  # @@protoc_insertion_point(class_scope:modi_cloud.TransferCompleteSend)
  })
_sym_db.RegisterMessage(TransferCompleteSend)

LearningCompleteSend = _reflection.GeneratedProtocolMessageType('LearningCompleteSend', (_message.Message,), {
  'DESCRIPTOR' : _LEARNINGCOMPLETESEND,
  '__module__' : 'modi_ai_cloud_pb2'
  # @@protoc_insertion_point(class_scope:modi_cloud.LearningCompleteSend)
  })
_sym_db.RegisterMessage(LearningCompleteSend)

TransferCompleteReply = _reflection.GeneratedProtocolMessageType('TransferCompleteReply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERCOMPLETEREPLY,
  '__module__' : 'modi_ai_cloud_pb2'
  # @@protoc_insertion_point(class_scope:modi_cloud.TransferCompleteReply)
  })
_sym_db.RegisterMessage(TransferCompleteReply)

LearningCompleteReply = _reflection.GeneratedProtocolMessageType('LearningCompleteReply', (_message.Message,), {
  'DESCRIPTOR' : _LEARNINGCOMPLETEREPLY,
  '__module__' : 'modi_ai_cloud_pb2'
  # @@protoc_insertion_point(class_scope:modi_cloud.LearningCompleteReply)
  })
_sym_db.RegisterMessage(LearningCompleteReply)

ModelReply = _reflection.GeneratedProtocolMessageType('ModelReply', (_message.Message,), {
  'DESCRIPTOR' : _MODELREPLY,
  '__module__' : 'modi_ai_cloud_pb2'
  # @@protoc_insertion_point(class_scope:modi_cloud.ModelReply)
  })
_sym_db.RegisterMessage(ModelReply)



_DATA_MODEL_HANDLER = _descriptor.ServiceDescriptor(
  name='Data_Model_Handler',
  full_name='modi_cloud.Data_Model_Handler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=335,
  serialized_end=488,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendObjects',
    full_name='modi_cloud.Data_Model_Handler.SendObjects',
    index=0,
    containing_service=None,
    input_type=_OBJECTSSEND,
    output_type=_MODELREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendObjectsAgain',
    full_name='modi_cloud.Data_Model_Handler.SendObjectsAgain',
    index=1,
    containing_service=None,
    input_type=_OBJECTSSEND,
    output_type=_MODELREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA_MODEL_HANDLER)

DESCRIPTOR.services_by_name['Data_Model_Handler'] = _DATA_MODEL_HANDLER


_COMPLETE_HANDLER = _descriptor.ServiceDescriptor(
  name='Complete_Handler',
  full_name='modi_cloud.Complete_Handler',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=491,
  serialized_end=687,
  methods=[
  _descriptor.MethodDescriptor(
    name='TransferComplete',
    full_name='modi_cloud.Complete_Handler.TransferComplete',
    index=0,
    containing_service=None,
    input_type=_TRANSFERCOMPLETESEND,
    output_type=_TRANSFERCOMPLETEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LearningComplete',
    full_name='modi_cloud.Complete_Handler.LearningComplete',
    index=1,
    containing_service=None,
    input_type=_LEARNINGCOMPLETESEND,
    output_type=_LEARNINGCOMPLETEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPLETE_HANDLER)

DESCRIPTOR.services_by_name['Complete_Handler'] = _COMPLETE_HANDLER

# @@protoc_insertion_point(module_scope)
